// type: 'fill' → tap the missing word
// type: 'order' → tap words in the correct order
export const ENGLISH_QUESTIONS = [

  // ── Grade 1 ──────────────────────────────────────────────────────────────────
  { grade:1, type:'fill', sentence:'The cat sat on the ___.', blank:'mat', choices:['mat','hat','bat'] },
  { grade:1, type:'fill', sentence:'I see a big red ___.', blank:'ball', choices:['ball','tall','wall'] },
  { grade:1, type:'fill', sentence:'The dog can ___.', blank:'run', choices:['run','sun','fun'] },
  { grade:1, type:'fill', sentence:'She has a ___ apple.', blank:'red', choices:['red','bed','fed'] },
  { grade:1, type:'fill', sentence:'He is my best ___.', blank:'friend', choices:['friend','blend','spend'] },
  { grade:1, type:'fill', sentence:'The bird can ___.', blank:'fly', choices:['fly','cry','try'] },
  { grade:1, type:'fill', sentence:'I ___ my hands before I eat.', blank:'wash', choices:['wash','cash','dash'] },
  { grade:1, type:'fill', sentence:'The baby ___ all night.', blank:'slept', choices:['slept','wept','kept'] },
  { grade:1, type:'fill', sentence:'We play in the ___ after school.', blank:'park', choices:['park','dark','mark'] },
  { grade:1, type:'fill', sentence:'The frog ___ into the pond.', blank:'jumped', choices:['jumped','bumped','pumped'] },
  { grade:1, type:'order', words:['I','like','cats'] },
  { grade:1, type:'order', words:['The','sun','is','hot'] },
  { grade:1, type:'order', words:['We','can','run','fast'] },
  { grade:1, type:'order', words:['My','dog','is','big'] },
  { grade:1, type:'order', words:['She','has','a','red','ball'] },
  { grade:1, type:'order', words:['The','cat','sat','down'] },

  // ── Grade 2 ──────────────────────────────────────────────────────────────────
  { grade:2, type:'fill', sentence:'She ___ to the store with her mom.', blank:'went', choices:['went','bent','lent'] },
  { grade:2, type:'fill', sentence:'The flowers ___ in the spring.', blank:'bloom', choices:['bloom','room','zoom'] },
  { grade:2, type:'fill', sentence:'We ___ our vegetables every day.', blank:'eat', choices:['eat','heat','seat'] },
  { grade:2, type:'fill', sentence:'He ___ his teeth before bed.', blank:'brushes', choices:['brushes','crushes','rushes'] },
  { grade:2, type:'fill', sentence:'The children ___ at the park.', blank:'played', choices:['played','stayed','prayed'] },
  { grade:2, type:'fill', sentence:'Rain ___ from the clouds.', blank:'falls', choices:['falls','calls','halls'] },
  { grade:2, type:'fill', sentence:'The puppy ___ its tail when happy.', blank:'wags', choices:['wags','bags','tags'] },
  { grade:2, type:'fill', sentence:'I ___ my book report last night.', blank:'finished', choices:['finished','punished','diminished'] },
  { grade:2, type:'fill', sentence:'The birds flew ___ to find warmer weather.', blank:'south', choices:['south','mouth','youth'] },
  { grade:2, type:'fill', sentence:'She was very ___ when she lost her toy.', blank:'sad', choices:['sad','bad','mad'] },
  { grade:2, type:'order', words:['The','rabbit','jumped','over','the','log'] },
  { grade:2, type:'order', words:['She','reads','books','every','night'] },
  { grade:2, type:'order', words:['My','sister','has','a','yellow','kite'] },
  { grade:2, type:'order', words:['I','love','to','eat','pizza'] },
  { grade:2, type:'order', words:['We','went','to','the','beach','today'] },
  { grade:2, type:'order', words:['The','dog','ran','across','the','yard'] },

  // ── Grade 3 ──────────────────────────────────────────────────────────────────
  { grade:3, type:'fill', sentence:'The scientist made an amazing ___.', blank:'discovery', choices:['discovery','recovery','delivery'] },
  { grade:3, type:'fill', sentence:'She felt very ___ when she won the race.', blank:'proud', choices:['proud','loud','crowd'] },
  { grade:3, type:'fill', sentence:'The library has ___ of books.', blank:'hundreds', choices:['hundreds','thunders','wonders'] },
  { grade:3, type:'fill', sentence:'He ___ to save money for a new bike.', blank:'decided', choices:['decided','provided','divided'] },
  { grade:3, type:'fill', sentence:'Animals that sleep during winter are in ___.', blank:'hibernation', choices:['hibernation','decoration','celebration'] },
  { grade:3, type:'fill', sentence:'She used a ___ to measure the wood.', blank:'ruler', choices:['ruler','cooler','mover'] },
  { grade:3, type:'fill', sentence:'The team showed great ___ by never giving up.', blank:'determination', choices:['determination','decoration','separation'] },
  { grade:3, type:'fill', sentence:'The map showed the ___ between the two cities.', blank:'distance', choices:['distance','instance','substance'] },
  { grade:3, type:'fill', sentence:'The author wrote a ___ story about a brave knight.', blank:'fictional', choices:['fictional','additional','traditional'] },
  { grade:3, type:'fill', sentence:'We need to ___ our natural resources.', blank:'protect', choices:['protect','correct','direct'] },
  { grade:3, type:'order', words:['The','puppy','chased','its','fluffy','tail'] },
  { grade:3, type:'order', words:['Every','morning','she','waters','her','plants'] },
  { grade:3, type:'order', words:['The','class','went','on','a','field','trip'] },
  { grade:3, type:'order', words:['He','carefully','placed','the','glass','on','the','shelf'] },
  { grade:3, type:'order', words:['The','wind','blew','the','leaves','off','the','tree'] },
  { grade:3, type:'order', words:['She','forgot','to','bring','her','lunch','to','school'] },

  // ── Grade 4 ──────────────────────────────────────────────────────────────────
  { grade:4, type:'fill', sentence:'The ancient ___ were built thousands of years ago.', blank:'pyramids', choices:['pyramids','periods','proverbs'] },
  { grade:4, type:'fill', sentence:'The author used vivid ___ to describe the sunset.', blank:'imagery', choices:['imagery','trickery','bravery'] },
  { grade:4, type:'fill', sentence:'She showed great ___ by helping her neighbor.', blank:'compassion', choices:['compassion','comparison','companion'] },
  { grade:4, type:'fill', sentence:'The volcano ___ after many years of quiet.', blank:'erupted', choices:['erupted','computed','corrupted'] },
  { grade:4, type:'fill', sentence:'The ___ of a triangle equals 180 degrees.', blank:'sum', choices:['sum','gum','drum'] },
  { grade:4, type:'fill', sentence:'The colonists wanted ___ from British rule.', blank:'independence', choices:['independence','indifference','inheritance'] },
  { grade:4, type:'fill', sentence:'Her essay had a clear ___ that stated her opinion.', blank:'thesis', choices:['thesis','feces','basis'] },
  { grade:4, type:'fill', sentence:'The ___ of the story was that hard work pays off.', blank:'moral', choices:['moral','coral','floral'] },
  { grade:4, type:'fill', sentence:'Scientists use ___ to test their ideas.', blank:'experiments', choices:['experiments','environments','enlargements'] },
  { grade:4, type:'fill', sentence:'The river flows ___ until it reaches the sea.', blank:'downstream', choices:['downstream','mainstream','upstream'] },
  { grade:4, type:'order', words:['Despite','the','rain','they','enjoyed','the','picnic'] },
  { grade:4, type:'order', words:['The','scientist','carefully','recorded','every','observation'] },
  { grade:4, type:'order', words:['Without','water','plants','cannot','survive'] },
  { grade:4, type:'order', words:['She','read','the','instructions','before','starting','the','experiment'] },
  { grade:4, type:'order', words:['The','explorers','mapped','rivers','and','mountains','they','discovered'] },
  { grade:4, type:'order', words:['Both','teams','played','hard','but','only','one','could','win'] },

  // ── Grade 5 ──────────────────────────────────────────────────────────────────
  { grade:5, type:'fill', sentence:'The author\'s ___ was to persuade the reader.', blank:'purpose', choices:['purpose','surplus','nervous'] },
  { grade:5, type:'fill', sentence:'The two candidates ___ their views during the debate.', blank:'contrasted', choices:['contrasted','contacted','contracted'] },
  { grade:5, type:'fill', sentence:'A ___ is a comparison using "like" or "as".', blank:'simile', choices:['simile','symbol','syllable'] },
  { grade:5, type:'fill', sentence:'Photosynthesis converts sunlight into ___.', blank:'energy', choices:['energy','entropy','empathy'] },
  { grade:5, type:'fill', sentence:'The ___ of a story is the main message or lesson.', blank:'theme', choices:['theme','scheme','dream'] },
  { grade:5, type:'fill', sentence:'Gravity ___ objects toward the center of the Earth.', blank:'pulls', choices:['pulls','hulls','dulls'] },
  { grade:5, type:'fill', sentence:'The senator gave a passionate ___ in support of the bill.', blank:'argument', choices:['argument','adjustment','agreement'] },
  { grade:5, type:'fill', sentence:'The ___ of a paragraph introduces the main idea.', blank:'topic sentence', choices:['topic sentence','conclusion','evidence','transition'] },
  { grade:5, type:'fill', sentence:'When two fractions have the same value, they are called ___ fractions.', blank:'equivalent', choices:['equivalent','irrelevant','eloquent'] },
  { grade:5, type:'fill', sentence:'An author\'s ___ is the attitude they have toward the subject.', blank:'tone', choices:['tone','tune','tame'] },
  { grade:5, type:'order', words:['Although','it','was','difficult','she','never','gave','up'] },
  { grade:5, type:'order', words:['The','constitution','protects','the','rights','of','citizens'] },
  { grade:5, type:'order', words:['In','order','to','succeed','one','must','practice','consistently'] },
  { grade:5, type:'order', words:['The','water','cycle','includes','evaporation','condensation','and','precipitation'] },
  { grade:5, type:'order', words:['Strong','evidence','supports','the','author\'s','central','argument'] },
  { grade:5, type:'order', words:['Scientists','use','data','to','draw','conclusions','about','the','world'] },
];
