export const READING_PASSAGES = [

  // ── Grade 1 ──────────────────────────────────────────────────────────────────

  {
    grade: 1,
    passage: 'Max is a little dog. He has brown fur and a wagging tail. Max loves to play fetch with his red ball.',
    question: 'What does Max love to do?',
    choices: ['Sleep all day', 'Play fetch', 'Eat fish', 'Climb trees'],
    answer: 1,
  },
  {
    grade: 1,
    passage: 'The sun rises every morning. It makes the sky turn pink and orange. Birds start to sing when the sun comes up.',
    question: 'What do birds do when the sun comes up?',
    choices: ['Go to sleep', 'Eat bugs', 'Start to sing', 'Swim in a lake'],
    answer: 2,
  },
  {
    grade: 1,
    passage: 'Lily has a pet fish named Bubbles. She feeds him every morning. Bubbles lives in a big glass bowl.',
    question: 'Where does Bubbles live?',
    choices: ['In a pond', 'In a big glass bowl', 'In the ocean', 'In a bathtub'],
    answer: 1,
  },
  {
    grade: 1,
    passage: 'It is raining outside. Tom puts on his yellow raincoat. He jumps in puddles on his way to school.',
    question: 'What color is Tom\'s raincoat?',
    choices: ['Red', 'Blue', 'Green', 'Yellow'],
    answer: 3,
  },
  {
    grade: 1,
    passage: 'Emma loves to help her mom bake cookies. They mix flour, sugar, and butter. Then they put the cookies in the oven.',
    question: 'What do Emma and her mom put in the oven?',
    choices: ['Bread', 'Cake', 'Cookies', 'Muffins'],
    answer: 2,
  },
  {
    grade: 1,
    passage: 'The cat sat on the window sill. She watched the birds fly by. She flicked her tail back and forth.',
    question: 'What did the cat watch?',
    choices: ['Dogs running', 'Birds flying', 'Cars driving', 'Children playing'],
    answer: 1,
  },
  {
    grade: 1,
    passage: 'Ben has a new red bike. He wears his helmet every time he rides. His dad taught him how to stop safely.',
    question: 'What does Ben wear when he rides?',
    choices: ['Glasses', 'A hat', 'A helmet', 'Gloves'],
    answer: 2,
  },
  {
    grade: 1,
    passage: 'Snow fell all night long. In the morning, everything was white. Sam ran outside to make a snowman.',
    question: 'What did Sam do in the morning?',
    choices: ['Made a snowman', 'Stayed inside', 'Went to school', 'Ate breakfast'],
    answer: 0,
  },
  {
    grade: 1,
    passage: 'Our class has a garden. We planted carrots and tomatoes. We water the plants every day so they grow big.',
    question: 'What do the students do every day to help the plants?',
    choices: ['Pick the vegetables', 'Add more seeds', 'Water the plants', 'Move them inside'],
    answer: 2,
  },
  {
    grade: 1,
    passage: 'The moon shines at night. It looks round and bright. Some nights it looks like a tiny sliver.',
    question: 'When does the moon shine?',
    choices: ['In the morning', 'At noon', 'At night', 'After breakfast'],
    answer: 2,
  },

  // ── Grade 2 ──────────────────────────────────────────────────────────────────

  {
    grade: 2,
    passage: 'Butterflies start as tiny eggs. The eggs hatch into caterpillars. After eating many leaves, the caterpillar makes a cocoon and becomes a beautiful butterfly.',
    question: 'What does a caterpillar do before it becomes a butterfly?',
    choices: ['It flies south', 'It makes a cocoon', 'It swims in water', 'It grows feathers'],
    answer: 1,
  },
  {
    grade: 2,
    passage: 'Mia loved going to the farmers market on Saturdays. She always chose the ripest strawberries and the freshest bread. Her favorite part was tasting the free samples.',
    question: 'What was Mia\'s favorite part of the market?',
    choices: ['Buying flowers', 'Meeting friends', 'Tasting free samples', 'Playing games'],
    answer: 2,
  },
  {
    grade: 2,
    passage: 'Penguins live in very cold places. They cannot fly, but they are excellent swimmers. Penguins huddle together to stay warm in the freezing wind.',
    question: 'How do penguins stay warm?',
    choices: ['They fly south', 'They wear coats', 'They dig tunnels', 'They huddle together'],
    answer: 3,
  },
  {
    grade: 2,
    passage: 'Our town has a big library. You can borrow books, DVDs, and even toys. A library card is free for everyone who lives in town.',
    question: 'What do you need to borrow things from the library?',
    choices: ['Money', 'A library card', 'A backpack', 'A parent note'],
    answer: 1,
  },
  {
    grade: 2,
    passage: 'Frogs begin their lives as eggs in the water. The eggs hatch into tadpoles with long tails. Over time, the tadpoles grow legs and lose their tails to become frogs.',
    question: 'What do tadpoles grow as they become frogs?',
    choices: ['Wings', 'Fins', 'Legs', 'Shells'],
    answer: 2,
  },
  {
    grade: 2,
    passage: 'Bears spend the winter in a deep sleep called hibernation. They eat a lot of food in the fall to store up fat. In spring, they wake up hungry.',
    question: 'Why do bears eat a lot in the fall?',
    choices: ['Because food tastes better then', 'To store up fat for winter', 'To grow bigger', 'To prepare for moving south'],
    answer: 1,
  },
  {
    grade: 2,
    passage: 'The post office is an important place in our community. Workers sort letters and packages and deliver them to homes and businesses. Without the post office, we could not send mail.',
    question: 'What do post office workers do with letters?',
    choices: ['They write them', 'They sell them', 'They sort and deliver them', 'They throw them away'],
    answer: 2,
  },
  {
    grade: 2,
    passage: 'Plants need sunlight, water, and soil to grow. The roots soak up water from the ground. The leaves use sunlight to make food for the plant.',
    question: 'What do the roots of a plant do?',
    choices: ['Make food from sunlight', 'Soak up water from the ground', 'Catch rain from the sky', 'Store sunlight'],
    answer: 1,
  },
  {
    grade: 2,
    passage: 'Rosa Parks refused to give up her seat on a bus in 1955. Her brave act helped spark the Civil Rights Movement. She showed that one person can make a big difference.',
    question: 'What did Rosa Parks do that was brave?',
    choices: ['She started a new school', 'She gave a speech', 'She refused to give up her bus seat', 'She marched to the capital'],
    answer: 2,
  },
  {
    grade: 2,
    passage: 'Spiders spin webs to catch insects for food. They make silk inside their bodies and push it out through tiny openings. Each web is a careful, sticky trap.',
    question: 'Why do spiders spin webs?',
    choices: ['To make a home to sleep in', 'To catch insects for food', 'To protect their eggs from rain', 'To climb trees faster'],
    answer: 1,
  },

  // ── Grade 3 ──────────────────────────────────────────────────────────────────

  {
    grade: 3,
    passage: 'The Amazon rainforest is home to millions of plants and animals. It covers most of northern Brazil. Scientists call it the "lungs of the Earth" because its trees produce so much oxygen.',
    question: 'Why do scientists call the Amazon the "lungs of the Earth"?',
    choices: ['It looks like a pair of lungs', 'Its trees produce a lot of oxygen', 'It is very hot and humid', 'Animals breathe underwater there'],
    answer: 1,
  },
  {
    grade: 3,
    passage: 'Thomas Edison tried thousands of materials before finding the right filament for his light bulb. When asked about his failures, he said he had simply found ten thousand ways that did not work. He never gave up.',
    question: 'What was Edison\'s attitude about his failed experiments?',
    choices: ['He was embarrassed by them', 'He quit after 100 tries', 'He blamed other scientists', 'He saw them as learning opportunities'],
    answer: 3,
  },
  {
    grade: 3,
    passage: 'Recycling helps reduce waste and protect the environment. When we recycle paper, we save trees. Recycling one aluminum can saves enough energy to power a TV for three hours.',
    question: 'What is one benefit of recycling aluminum cans?',
    choices: ['It makes new paper', 'It cleans the ocean', 'It saves energy', 'It plants new trees'],
    answer: 2,
  },
  {
    grade: 3,
    passage: 'Every winter, monarch butterflies migrate from Canada all the way to Mexico — a journey of over 3,000 miles. They travel in huge groups and use the position of the sun to navigate.',
    question: 'How do monarch butterflies navigate during migration?',
    choices: ['They follow rivers', 'They use the position of the sun', 'They follow other birds', 'They use their sense of smell'],
    answer: 1,
  },
  {
    grade: 3,
    passage: 'The ancient Egyptians built the pyramids as tombs for their pharaohs. Workers moved giant stone blocks weighing thousands of pounds. Scientists still debate exactly how they did it.',
    question: 'What were the Egyptian pyramids built for?',
    choices: ['As temples for worship', 'As tombs for pharaohs', 'As storage for grain', 'As homes for workers'],
    answer: 1,
  },
  {
    grade: 3,
    passage: 'Water exists in three forms: liquid, solid, and gas. When water freezes, it becomes ice. When it heats up, it turns into steam. These changes happen all around us every day.',
    question: 'What happens to water when it freezes?',
    choices: ['It becomes steam', 'It disappears', 'It becomes ice', 'It turns salty'],
    answer: 2,
  },
  {
    grade: 3,
    passage: 'The school library is more than just a place for books. Students can use computers, attend reading clubs, and get help from the librarian with research projects. It is a center for learning.',
    question: 'According to the passage, what can students do in the school library?',
    choices: ['Only read books quietly', 'Use computers and attend clubs', 'Watch movies and play games', 'Cook food for lunch'],
    answer: 1,
  },
  {
    grade: 3,
    passage: 'George Washington Carver was a scientist who discovered hundreds of uses for peanuts. He helped poor Southern farmers by showing them new crops to grow. He is remembered as one of America\'s greatest agricultural scientists.',
    question: 'How did Carver help poor Southern farmers?',
    choices: ['By giving them money', 'By building better tools', 'By showing them new crops to grow', 'By teaching them to read'],
    answer: 2,
  },
  {
    grade: 3,
    passage: 'Earthquakes happen when large pieces of Earth\'s crust shift suddenly. The shaking can damage buildings and roads. Scientists use instruments called seismographs to measure earthquakes.',
    question: 'What do scientists use to measure earthquakes?',
    choices: ['Thermometers', 'Telescopes', 'Compasses', 'Seismographs'],
    answer: 3,
  },
  {
    grade: 3,
    passage: 'In a community, people depend on each other. Doctors keep us healthy, teachers help us learn, and firefighters keep us safe. Working together makes communities stronger.',
    question: 'What is the main idea of this passage?',
    choices: ['Doctors are the most important workers', 'Communities need many different types of workers', 'Teachers earn the most money', 'Firefighters are the bravest people'],
    answer: 1,
  },

  // ── Grade 4 ──────────────────────────────────────────────────────────────────

  {
    grade: 4,
    passage: 'The water cycle is the continuous movement of water on Earth. Water evaporates from oceans and lakes, rises as water vapor, cools to form clouds, and falls back to Earth as precipitation. This cycle keeps our planet\'s water supply balanced.',
    question: 'What happens to water vapor when it rises and cools?',
    choices: ['It evaporates again', 'It falls immediately as rain', 'It forms clouds', 'It becomes ice underground'],
    answer: 2,
  },
  {
    grade: 4,
    passage: 'During the American Revolution, colonists were frustrated by taxation without representation in the British Parliament. They believed that laws affecting them should only be made by people they elected. This idea became a cornerstone of American democracy.',
    question: 'What did colonists mean by "taxation without representation"?',
    choices: ['They paid too many taxes', 'Laws were made by people they did not elect', 'They wanted free trade with France', 'British soldiers lived in their homes'],
    answer: 1,
  },
  {
    grade: 4,
    passage: 'Volcanoes form where tectonic plates meet or separate. Molten rock called magma rises through vents in Earth\'s crust. When magma reaches the surface, it is called lava. Over thousands of years, cooled lava can build entire islands.',
    question: 'What is magma called once it reaches Earth\'s surface?',
    choices: ['Tectite', 'Granite', 'Basalt', 'Lava'],
    answer: 3,
  },
  {
    grade: 4,
    passage: 'The food web shows how energy moves through an ecosystem. Plants make their own food from sunlight. Herbivores eat plants, and carnivores eat herbivores. When anything dies, decomposers break it down and return nutrients to the soil.',
    question: 'What role do decomposers play in the food web?',
    choices: ['They eat carnivores', 'They produce sunlight for plants', 'They break down dead things and return nutrients to soil', 'They carry seeds to new places'],
    answer: 2,
  },
  {
    grade: 4,
    passage: 'Abraham Lincoln issued the Emancipation Proclamation in 1863. It declared that enslaved people in Confederate states were free. While it did not immediately free all enslaved people, it changed the meaning of the Civil War.',
    question: 'What did the Emancipation Proclamation declare?',
    choices: ['That the Civil War was over', 'That enslaved people in Confederate states were free', 'That all states must rejoin the Union', 'That women could vote'],
    answer: 1,
  },
  {
    grade: 4,
    passage: 'A narrative essay tells a personal story. It uses descriptive details to bring events to life for the reader. Unlike a report, a narrative includes the writer\'s own thoughts and feelings about what happened.',
    question: 'How is a narrative essay different from a report?',
    choices: ['It is always shorter', 'It must use facts only', 'It includes the writer\'s thoughts and feelings', 'It is written by multiple authors'],
    answer: 2,
  },
  {
    grade: 4,
    passage: 'Rainforests receive more than 80 inches of rainfall per year. The trees form a thick canopy that blocks most sunlight from reaching the forest floor. Plants and animals have developed incredible adaptations to survive in this environment.',
    question: 'What does the canopy in a rainforest do?',
    choices: ['It filters pollution from the air', 'It blocks most sunlight from reaching the floor', 'It stores water for dry seasons', 'It provides fruit for animals'],
    answer: 1,
  },
  {
    grade: 4,
    passage: 'Fractions represent parts of a whole. When the numerator and denominator are the same, the fraction equals one whole. To add fractions with the same denominator, you simply add the numerators and keep the denominator the same.',
    question: 'When adding fractions with the same denominator, what do you keep the same?',
    choices: ['The numerator', 'Both numbers', 'The denominator', 'Neither number'],
    answer: 2,
  },
  {
    grade: 4,
    passage: 'Harriet Tubman escaped slavery in 1849 and then returned south many times to lead others to freedom on the Underground Railroad. She never lost a single passenger. During the Civil War she also served as a spy for the Union Army.',
    question: 'What was remarkable about Harriet Tubman\'s Underground Railroad journeys?',
    choices: ['She traveled by boat', 'She never lost a single passenger', 'She only helped her family', 'She traveled only at daytime'],
    answer: 1,
  },
  {
    grade: 4,
    passage: 'When authors write, they choose words carefully to create a tone. A serious tone uses formal language. A humorous tone might include jokes or exaggeration. Recognizing tone helps readers understand the author\'s purpose.',
    question: 'According to the passage, what helps readers understand an author\'s purpose?',
    choices: ['Counting the words used', 'Recognizing the tone', 'Reading very slowly', 'Skipping difficult words'],
    answer: 1,
  },

  // ── Grade 5 ──────────────────────────────────────────────────────────────────

  {
    grade: 5,
    passage: 'Photosynthesis is the process plants use to convert sunlight, water, and carbon dioxide into glucose and oxygen. The chlorophyll in plant leaves absorbs sunlight to power this reaction. Without photosynthesis, most life on Earth could not exist.',
    question: 'Which substance in plant leaves absorbs sunlight for photosynthesis?',
    choices: ['Glucose', 'Cellulose', 'Carbon dioxide', 'Chlorophyll'],
    answer: 3,
  },
  {
    grade: 5,
    passage: 'In a persuasive essay, the author\'s goal is to change the reader\'s mind or inspire action. Strong persuasive writing uses evidence, logical reasoning, and emotional appeals. Understanding the audience helps a writer choose the most effective arguments.',
    question: 'What is the primary goal of a persuasive essay?',
    choices: ['To tell a fictional story', 'To describe a personal experience', 'To change the reader\'s mind or inspire action', 'To explain how something works'],
    answer: 2,
  },
  {
    grade: 5,
    passage: 'The Constitution created a system of checks and balances among the three branches of government. Congress makes laws, the President enforces them, and the Supreme Court interprets them. Each branch has powers to limit the other two, preventing any one branch from becoming too powerful.',
    question: 'What is the purpose of the system of checks and balances?',
    choices: ['To make laws quickly', 'To prevent any one branch from becoming too powerful', 'To allow the President to overrule Congress', 'To speed up Supreme Court decisions'],
    answer: 1,
  },
  {
    grade: 5,
    passage: 'Newton\'s first law of motion states that an object at rest stays at rest, and an object in motion stays in motion, unless acted upon by an outside force. This is also known as the law of inertia. Friction and gravity are common forces that slow moving objects.',
    question: 'What is Newton\'s first law of motion also known as?',
    choices: ['The law of gravity', 'The law of acceleration', 'The law of inertia', 'The law of momentum'],
    answer: 2,
  },
  {
    grade: 5,
    passage: 'The Civil Rights Act of 1964 outlawed discrimination based on race, color, religion, sex, or national origin. It was a landmark law that changed American society. The act gave the federal government power to enforce desegregation in schools and public places.',
    question: 'What did the Civil Rights Act of 1964 outlaw?',
    choices: ['Unfair voting rules only', 'Discrimination based on race, color, religion, sex, or national origin', 'All forms of protest', 'Segregation in the military only'],
    answer: 1,
  },
  {
    grade: 5,
    passage: 'Ecosystems can be damaged by both natural events and human activities. Wildfires, floods, and droughts are natural disturbances. Pollution, deforestation, and urban sprawl are human-caused threats. Conservation efforts aim to restore balance to damaged ecosystems.',
    question: 'Which of the following is a human-caused threat to ecosystems?',
    choices: ['Wildfires', 'Floods', 'Deforestation', 'Droughts'],
    answer: 2,
  },
  {
    grade: 5,
    passage: 'Figurative language helps writers express ideas in creative ways. A metaphor says one thing IS another, while a simile compares using "like" or "as." Personification gives human qualities to non-human things. Hyperbole uses extreme exaggeration for effect.',
    question: 'What is the difference between a metaphor and a simile?',
    choices: ['A metaphor rhymes; a simile does not', 'A simile is longer than a metaphor', 'A metaphor says one thing IS another; a simile uses "like" or "as"', 'There is no difference between them'],
    answer: 2,
  },
  {
    grade: 5,
    passage: 'The solar system formed about 4.6 billion years ago from a cloud of gas and dust. Gravity pulled the material together to form the sun. Leftover material clumped together to form the planets, moons, and asteroids we see today.',
    question: 'What force caused the solar system\'s gas and dust to come together?',
    choices: ['Magnetism', 'Gravity', 'Solar wind', 'Rotation'],
    answer: 1,
  },
  {
    grade: 5,
    passage: 'Supply and demand is a basic principle of economics. When supply is low and demand is high, prices tend to rise. When supply is high and demand is low, prices tend to fall. This relationship influences what things cost in a market economy.',
    question: 'What happens to prices when supply is low and demand is high?',
    choices: ['Prices fall', 'Prices stay the same', 'Prices rise', 'Prices are controlled by the government'],
    answer: 2,
  },
  {
    grade: 5,
    passage: 'Marie Curie was the first woman to win a Nobel Prize, and she won it twice — once in Physics and once in Chemistry. She discovered two new elements: polonium and radium. Her research on radioactivity changed science forever.',
    question: 'What made Marie Curie\'s Nobel Prize wins especially historic?',
    choices: ['She won them both in the same year', 'She shared them with her husband', 'She was the first woman to win one, and she won twice', 'She won them while still a student'],
    answer: 2,
  },
];
